name: ESLint                                              # Define the name of the workflow

on: [push, pull_request]                                  # Trigger the workflow on push and pull request events

jobs:                                                     # Initialise job
  lint:                                                   # Define a job named 'lint'
    runs-on: ubuntu-latest                                # Specifies the type of VM to provision

    container:                                            # Set container image
      image: monkeyknuckles/test                          # Points to Python container

    steps:                                                # List of steps to execute
      - name: Checkout code                               # Checkout code label text
        uses: actions/checkout@v3                         # Use the checkout action to clone the repository

      - name: Copy Pylint config                          # Copy ESLint configuration file label text
        run: cp /app/.pylintrc $GITHUB_WORKSPACE          # Include the Pylint configuration file in the docker build

      - name: Run Lint Pylint                             # Set lint Pylint label text
        run: |                                            # Find and lint all Python files
             find . -type f -name "*.py" -print0 | 
             xargs -0 pylint # Lint all Python files